name: Update R2 URLs List

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Allows pushing changes to the repo

jobs:
  update-r2-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2  # Installs AWS CLI v2

      - name: List all object URLs
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "auto"
        run: |
          aws s3api list-objects-v2 \
            --endpoint-url ${{ vars.R2_ENDPOINT_URL }} \
            --bucket ${{ vars.R2_BUCKET_NAME }} \
            --query 'Contents[*].Key' \
            --output json | jq -r '.[] | "${{ vars.R2_PUBLIC_BASE_URL }}/" + .' > ${{ vars.URLS_FILE }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull origin main
          git add ${{ vars.URLS_FILE }}
          git diff --staged --quiet || (git commit -m "Update R2 URLs list" && git push origin main)
